export  const themes = {
    grayscale: {
        "--lightest":" #e2e2e2",
        "--middle-light":"#e2e2e2 ",
        "--middle":" #e2e2e2",
        "--middle-dark":" #242526",
        "--darkest":" #171717",
        "--main-font":"'Comfortaa', cursive",
        "--main-background":"#b0b3b8",
        "--main-background-text":"white",
        "--header-background":"#e2e2e2",
        "--header-text":"#000000",
        "--header-sub-text":"#000000",
        "--nav-background-color":"#000000",
        "--nav-hover":"#000000",
        "--nav-text-color":"#e2e2e2",
        "--task-header-background":"#000000",
        "--task-header-color":"#e2e2e2",
        "--task-body-background":"#e2e2e2",
        "--table-background":"#e2e2e2",
        "--table-header":"#e2e2e2",
        "--table-header-text":"#000000",
        "--table-text-color":"black",
        "--input-background":"#e2e2e2",
        "--input-color":"#000000",
        "--default-text":"rgb(38, 25, 68)",
        "--chart-text":"black",
        "--table-top":"#000000",
        "--table-top-text":"rgb(255, 255, 255)",
        "--poppin-border":"rgb(255, 236, 68)",
        "--big-button-background":"#000000",
        "--big-button-text":"#e2e2e2",
        "--report-text":"#000000",
        "--add-product-background":"#e2e2e2",
        "--add-product-text":"#000000",
    },
    aqua:{  
        "--main-text":"hsl(182, 21%, 47%)",
        "--main-background":"hsl(182, 21%, 47%)",
        "--card-background":"hsl(182, 36%, 86%)",
        "--middle-dark":" rgb(36, 38, 38)",
        "--darkest":" #022b29",
        "--poppin-border":"rgb(218, 177, 89)",
        "--main-font":"'Karla', sans-serif",
    "--lightest":" var(--card-background)",
    "--middle-light":"var(--card-background) ",
    "--middle":" var(--card-background)",
    "--main-background-text":"var(--card-background)",
    "--header-background":"var(--card-background)",
    "--header-text":"  var(--main-text)",
    "--header-sub-text":"  var(--main-text)",
    "--nav-background-color":"  var(--main-text)",
    "--nav-hover":"  var(--main-text)",
    "--nav-text-color":"var(--card-background)",
    "--task-header-background":"  var(--main-text)",
    "--task-header-color":"var(--card-background)",
    "--task-body-background":"var(--card-background)",
    "--table-background":"var(--card-background)",
    "--table-header":"var(--card-background)",
    "--table-header-text":"  var(--main-text)",
    "--table-text-color":"  var(--main-text)",
    "--input-background":"var(--card-background)",
    "--input-color":"var(--main-text)",
    "--default-text":"var(--main-text)",
    "--chart-text":"  var(--main-text)",
    "--table-top":"  var(--main-text)",
    "--table-top-text":"var(--card-background)",
    "--big-button-background":"  var(--main-text)",
    "--big-button-text":"var(--card-background)",
    "--report-text":"  var(--middle-dark)",
    "--add-product-background":"var(--card-background)",
    "--add-product-text":"  var(--main-text)"},
    babyBlue: {
        "--main-text":"hsl(199, 57%, 39%)",
        "--main-background":"hsl(221deg 100% 96%)",
        "--card-background":"hsl(221deg 100% 90%)",
        "--middle-dark":" rgb(36, 38, 38)",
        "--darkest":" #022b29",
        "--poppin-border":"rgb(218, 177, 89)",
        "--main-font":"'Josefin Sans', sans-serif",
        "--lightest":" var(--card-background)",
        "--middle-light":"var(--card-background) ",
        "--middle":" var(--card-background)",
        "--main-background-text":"var(--card-background)",
        "--header-background":"var(--card-background)",
        "--header-text":"  var(--main-text)",
        "--header-sub-text":"  var(--main-text)",
        "--nav-background-color":"  var(--main-text)",
        "--nav-hover":"  var(--main-text)",
        "--nav-text-color":"var(--card-background)",
        "--task-header-background":"  var(--main-text)",
        "--task-header-color":"var(--card-background)",
        "--task-body-background":"var(--card-background)",
        "--table-background":"var(--card-background)",
        "--table-header":"var(--card-background)",
        "--table-header-text":"  var(--main-text)",
        "--table-text-color":"  var(--main-text)",
        "--input-background":"var(--card-background)",
        "--input-color":"var(--main-text)",
        "--default-text":"var(--main-text)",
        "--chart-text":"  var(--main-text)",
        "--table-top":"  var(--main-text)",
        "--table-top-text":"var(--card-background)",
        "--big-button-background":"  var(--main-text)",
        "--big-button-text":"var(--card-background)",
        "--report-text":"  var(--middle-dark)",
        "--add-product-background":"var(--card-background)",
        "--add-product-text":"  var(--main-text)"},
    space:{  "--lightest":" #da6d6d",
    "--middle-light":"rgb(255, 236, 68) ",
    "--middle":" rgb(255, 236, 68)",
    "--middle-dark":" #242526",
    "--darkest":" #171717",
    "--main-font":"'Space Mono', monospace",
    "--main-background":"#0a0a0a",
    "--main-background-text":"white",
    "--header-background":"rgb(0, 24, 70)",
    "--header-text":"rgb(255, 236, 68)",
    "--header-sub-text":"rgb(177, 192, 90)",
    "--nav-background-color":"rgb(255, 236, 68)",
    "--nav-hover":"rgb(255, 236, 68)",
    "--nav-text-color":"black",
    "--task-header-background":"rgb(9, 19, 75)",
    "--task-header-color":"rgb(255, 236, 68)",
    "--task-body-background":"rgb(252, 242, 105)",
    "--table-background":"rgb(232, 233, 248)",
    "--table-header":"rgb(0, 24, 70)",
    "--table-header-text":"white",
    "--table-text-color":"black",
    "--input-background":"rgb(0, 24, 70)",
    "--input-color":"rgb(228, 180, 228)",
    "--default-text":"rgb(38, 25, 68)",
    "--chart-text":"black",
    "--table-top":"rgb(38, 25, 68)",
    "--table-top-text":"rgb(255, 255, 255)",
    "--poppin-border":"rgb(255, 236, 68)",
    "--big-button-background":"rgb(38, 25, 68)",
    "--big-button-text":"white",
    "--report-text":"white"},
}

